version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t company/app:$CIRCLE_BRANCH .
