name: Update Docker Hub Description

on:
  release:
    types: [published, released, edited]
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
      
jobs:
  dockerHubDescription:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_R_PWD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/warddashboard
        short-description: ${{ github.event.repository.description }}
