name: Java Linter
on: [push]

jobs:
  checkstyle_job:
    runs-on: self-hosted
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.G_TOKEN }}
        reporter: 'github-pr-check'
        tool_name: 'TestTool'
