name: Build Docker Image

on:
  release:
    types: [published, released, edited, created]
    tags:
      - v*
  workflow_dispatch:

env:
  APP_NAME: ${{ github.event.repository.name }}
  DOCKERHUB: ${{ github.event.repository.name }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Repo name to-lower-case
        run: echo DOCKERHUB_REPO=${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKERHUB.lowercase }} >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:

          push: true
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8

          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}

          tags: ${{ env.DOCKERHUB_REPO }}:${{ steps.meta.outputs.tags }}-${{ steps.time.outputs.time }}
